version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:17.2.0-buster-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          key: zeus-ui-3.0-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: zeus-ui-3.0-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test -- --watch=false --no-progress --browsers=ChromeNoSandbox
      - run: xvfb-run -a npm run start
#      - run: xvfb-run -a npm run start -- --configuration=../protractor-ci.conf.js
