version: 2.1
orbs:
  jira: circleci/jira@1.0.5
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
#    working_directory: ~/my-project
    docker:
#      - image: cimg/node:16.13.1-browsers
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - restore_cache:
          key: zeus-ui-3.0-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: zeus-ui-3.0-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run build --prod
#      - store_aritfacts:
#          path: dist/my-app
#          destination: my-app
  test:
    docker:
      - image: circleci/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run test
workflows:
  build-and-test:
    jobs:
      - build:
          post-steps:
            - jira/notify
      - test
