version: 2.1
orbs:
  jira: circleci/jira@1.0.5
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - restore_cache:
          key: zeus-ui-3.0-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: zeus-ui-3.0-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --watch=false --no-progress --browsers=ChromeNoSandbox
#      - run: xvfb-run -a npm run start
#      - run: xvfb-run -a npm run start -- --configuration=../protractor-ci.conf.js
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
