version: 2.1
orbs:
  jira: circleci/jira@1.0.5
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
#      - image: cimg/node:16.13.1-browsers
      - image: circleci/node:14.17.1
    steps:
      - checkout
      - restore_cache:
          key: zeus-ui-3.0-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: zeus-ui-3.0-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run build --prod
  test:
    docker:
      - image: circleci/node:14.17.1-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: echo $API_URL
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run test
workflows:
  build-and-test:
    environment:
      API_URL: "http://localhost:80"
    jobs:
      - build:
          post-steps:
            - jira/notify
      - test:
          requires:
            - build

